<?php
    session_start();
    define("APP_ID",'6142618');
    define("APP_SECRET",'eOedUJx484isDHABhtV6');
    define("REDIRECT_URI",'http://t-platform.xyz/auth.php');
    define("URL_ACCESS_TOKEN",'https://oauth.vk.com/access_token');
    define("URL_AUTH",'http://oauth.vk.com/authorize');
    define("URL_GET_FRIENDS",'https://api.vk.com/method/friends.get');
    define("URL_GET_USER",'https://api.vk.com/method/users.get');
?>